### Pesquisar Procedimentos por Grupo
POST https://servicos.saude.gov.br/sigtap/ProcedimentoService/v1
Content-Type: application/soap+xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"
xmlns:proc="http://servicos.saude.gov.br/sigtap/v1/procedimentoservice"
xmlns:grup="http://servicos.saude.gov.br/schema/sigtap/procedimento/nivelagregacao/v1/grupo"
xmlns:sub="http://servicos.saude.gov.br/schema/sigtap/procedimento/nivelagregacao/v1/subgrupo"
xmlns:com="http://servicos.saude.gov.br/schema/corporativo/v1/competencia"
xmlns:pag="http://servicos.saude.gov.br/wsdl/mensageria/v1/paginacao">
  <soap:Header>
    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
      <wsse:UsernameToken wsu:Id="Id-0001334008436683-000000002c4a1908-1" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsse:Username>SIGTAP.PUBLICO</wsse:Username>
        <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">sigtap#2015public</wsse:Password>
      </wsse:UsernameToken>
    </wsse:Security>
  </soap:Header>
  <soap:Body>
    <proc:requestPesquisarProcedimentos>
      <grup:codigoGrupo>05</grup:codigoGrupo>
      <sub:codigoSubgrupo>04</sub:codigoSubgrupo>
      <com:competencia>201501</com:competencia>
      <pag:Paginacao>
        <pag:registroInicial>01</pag:registroInicial>
        <pag:quantidadeRegistros>20</pag:quantidadeRegistros>
        <pag:totalRegistros>100</pag:totalRegistros>
      </pag:Paginacao>
    </proc:requestPesquisarProcedimentos>
  </soap:Body>
</soap:Envelope>

### Detalhar Procedimentos (Identificar CBOs)
POST https://servicos.saude.gov.br/sigtap/ProcedimentoService/v1
Content-Type: application/soap+xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"
xmlns:proc="http://servicos.saude.gov.br/sigtap/v1/procedimentoservice"
xmlns:proc1="http://servicos.saude.gov.br/schema/sigtap/procedimento/v1/procedimento"
xmlns:com="http://servicos.saude.gov.br/schema/corporativo/v1/competencia"
xmlns:det="http://servicos.saude.gov.br/wsdl/mensageria/sigtap/v1/detalheadicional"
xmlns:pag="http://servicos.saude.gov.br/wsdl/mensageria/v1/paginacao">
  <soap:Header>
    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
      <wsse:UsernameToken wsu:Id="Id-0001334008436683-000000002c4a1908-1" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsse:Username>SIGTAP.PUBLICO</wsse:Username>
        <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">sigtap#2015public</wsse:Password>
      </wsse:UsernameToken>
    </wsse:Security>
  </soap:Header>
  <soap:Body>
    <proc:requestDetalharProcedimento>
      <proc1:codigoProcedimento>0203010027</proc1:codigoProcedimento>
      <proc:DetalhesAdicionais>
        <det:DetalheAdicional>
          <det:categoriaDetalheAdicional>CBOS</det:categoriaDetalheAdicional>
          <det:Paginacao>
            <pag:registroInicial>1</pag:registroInicial>
            <pag:quantidadeRegistros>20</pag:quantidadeRegistros>
            <pag:totalRegistros>100</pag:totalRegistros>
          </det:Paginacao>
        </det:DetalheAdicional>
      </proc:DetalhesAdicionais>
    </proc:requestDetalharProcedimento>
  </soap:Body>
</soap:Envelope>